DIRECTIONS = UP, LEFT, DOWN, RIGHT = 'U', 'L', 'D', 'R'

TILE_VALUES = FOOD, POISON, EMPTY = 'FOOD', 'POISON', 'EMPTY'

AGENT_MOVES = MOVE_FORWARD, MOVE_LEFT, MOVE_RIGHT, NO_OPERATION = 'FORWARD', 'LEFT', 'RIGHT', 'NOOP'

DIRECTION_VALUES = {
    UP: (0, -1),
    LEFT: (-1, 0),
    DOWN: (0, 1),
    RIGHT: (1, 0),
}
